### ISSUE TITLE
Add a requirements.txt file

### ISSUE THREAD

**Issue by kurosakishigure** [tobiasGuta/sub-enum#2]
**Is your feature request related to a problem? Please describe.**

If I want to clone this project locally, the absence of a `requirements.txt` file makes it difficult to determine which dependencies need to be installed.

**Describe the solution you'd like**

Adding a `requirements.txt` file to the root directory of the project would solve this issue. Once I clone the project, I could simply run the following command in the root directory to install all the necessary dependencies in one step:

```bash
pip install -r requirements.txt
```

**Describe alternatives you've considered**

While we could also create an `INSTALL.md` file to document all the required dependencies, it’s less convenient.

**Additional context**

To get started, we need to identify all the necessary dependencies for the project. For example, as referenced here:  
[https://github.com/tobiasGuta/sub-enum/blob/bc1086b603ab62009ae5bfaf250a5eaf58fd328b/sub.py#L2](https://github.com/tobiasGuta/sub-enum/blob/bc1086b603ab62009ae5bfaf250a5eaf58fd328b/sub.py#L2)

Next, add `requests` to the `requirements.txt` file. If version compatibility is a concern, we might also need to specify and lock dependency versions. For more details, refer to the [Requirements File Format](https://pip.pypa.io/en/stable/reference/requirements-file-format/).

**Comment by kurosakishigure** [comment]
Unfortunately, it seems I can't manually assign a label to this issue. It might be more appropriate to categorize it as an `enhancement`.

**Comment by tobiasGuta** [comment]
Yes, the absence of a requirements.txt file makes it difficult to determine and install the necessary dependencies when cloning the project. I have already created a bash script called install_tools.sh that automates the installation of all dependencies, including both system-wide and Python packages

**Comment by tobiasGuta** [comment]
Thank you for the suggestion! I’ve added a requirements.txt file to the project, which now includes the necessary Python dependencies (e.g., requests). This should make it easier to install the required libraries.

**Comment by kurosakishigure** [comment]
Happy coding!
